name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/z.csproj
          PACKAGE_NAME: dotnet-cli-zip
          VERSION_FILE_PATH: z.csproj
          VERSION_REGEX: <Version>(.*)<\/Version>
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.DOTNET_CLI_ZIP}}
          INCLUDE_SYMBOLS: true